
'''
    此文件中存储UTRflySim中的常量字符串
'''

# 仿真方案类型
PROPOSAL_TYPE_PLANNING_CONTROL = "规划管控"
PROPOSAL_TYPE_OBSTACLE_AVOIDANCE = "感知避障"
PROPOSAL_TYPE_COMMUNICATION_COOPERATION = "通信协同"

## 仿真模式
PROPOSAL_SIMULATION_MODE_PARTICLE = "质点模式"
PROPOSAL_SIMULATION_MODE_FULL_STATE = "全状态模式"

# 仿真方案运行状态
PROPOSAL_STATUS_STOP = "停止"
PROPOSAL_STATUS_LAUNCHING = "启动中"
PROPOSAL_STATUS_RUN = "运行"
PROPOSAL_STATUS_PAUSE = "暂停"
PROPOSAL_STATUS_STOPING = "停止中"

# 节点类型
NETWORK_NODE_TYPE_JUNCTION = "交叉口"
NETWORK_NODE_TYPE_ENTRANCE = "出入口"
NETWORK_NODE_TYPE_VIRTUAL = "虚拟节点"

# 航路联接类型
NETWORK_LINKAGE_TYPE_PREDECESSOR = "前继"
NETWORK_LINKAGE_TYPE_SUCCESSOR = "后继"

# 航路管控类型
NETWORK_CONTROL_TYPE_0 = "按权限通过"
NETWORK_CONTROL_TYPE_1 = "限流"
NETWORK_CONTROL_TYPE_2 = "限速"

# 故障类型……
FAULT_TYPE_NON_COOPERATIVE_OBSTACLE = "非合作障碍物"


# 评估类型……


# 评估指标名称……
